//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaNa.Multilanguage {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmaNa.Multilanguage.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Termin hinzufügen ähnelt.
        /// </summary>
        public static string addAppointment {
            get {
                return ResourceManager.GetString("addAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuen Termin erfassen ähnelt.
        /// </summary>
        public static string addNewAppointment {
            get {
                return ResourceManager.GetString("addNewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colonkarzinom ähnelt.
        /// </summary>
        public static string Colonkarzinom {
            get {
                return ResourceManager.GetString("Colonkarzinom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Termin ähnelt.
        /// </summary>
        public static string EditTerminDate {
            get {
                return ResourceManager.GetString("EditTerminDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durchführender Arzt ähnelt.
        /// </summary>
        public static string EditTerminDoctor {
            get {
                return ResourceManager.GetString("EditTerminDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Termin durchgeführt ähnelt.
        /// </summary>
        public static string EditTerminDone {
            get {
                return ResourceManager.GetString("EditTerminDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Termin abgemacht ähnelt.
        /// </summary>
        public static string EditTerminFixed {
            get {
                return ResourceManager.GetString("EditTerminFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ort ähnelt.
        /// </summary>
        public static string EditTerminLocation {
            get {
                return ResourceManager.GetString("EditTerminLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminname ähnelt.
        /// </summary>
        public static string EditTerminName {
            get {
                return ResourceManager.GetString("EditTerminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminperiode ähnelt.
        /// </summary>
        public static string EditTerminPeriode {
            get {
                return ResourceManager.GetString("EditTerminPeriode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erinnern ähnelt.
        /// </summary>
        public static string EditTerminRemind {
            get {
                return ResourceManager.GetString("EditTerminRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meine Termine ähnelt.
        /// </summary>
        public static string MainMenuAppointments {
            get {
                return ResourceManager.GetString("MainMenuAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meine Operation ähnelt.
        /// </summary>
        public static string MainMenuOperation {
            get {
                return ResourceManager.GetString("MainMenuOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string MainMenuSettings {
            get {
                return ResourceManager.GetString("MainMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen bei deiner smarten Nachsorge! ähnelt.
        /// </summary>
        public static string MainMenuWelcome {
            get {
                return ResourceManager.GetString("MainMenuWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rektumkarzinom ähnelt.
        /// </summary>
        public static string Rektumkarzinom {
            get {
                return ResourceManager.GetString("Rektumkarzinom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Termin speichern ähnelt.
        /// </summary>
        public static string saveAppointment {
            get {
                return ResourceManager.GetString("saveAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen speichern ähnelt.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Karzinomart ähnelt.
        /// </summary>
        public static string SettingsCarcinomType {
            get {
                return ResourceManager.GetString("SettingsCarcinomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OP-Datum ähnelt.
        /// </summary>
        public static string SettingsOPDate {
            get {
                return ResourceManager.GetString("SettingsOPDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volles Stageing ähnelt.
        /// </summary>
        public static string SettingsStageingComplete {
            get {
                return ResourceManager.GetString("SettingsStageingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TNM ähnelt.
        /// </summary>
        public static string SettingsTNM {
            get {
                return ResourceManager.GetString("SettingsTNM", resourceCulture);
            }
        }
    }
}
