//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmaNa.Multilanguage {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmaNa.Multilanguage.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin hinzufügen.
        /// </summary>
        public static string addAppointment {
            get {
                return ResourceManager.GetString("addAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Termin erfassen.
        /// </summary>
        public static string addNewAppointment {
            get {
                return ResourceManager.GetString("addNewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonkarzinom.
        /// </summary>
        public static string Colonkarzinom {
            get {
                return ResourceManager.GetString("Colonkarzinom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin.
        /// </summary>
        public static string EditTerminDate {
            get {
                return ResourceManager.GetString("EditTerminDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arzt.
        /// </summary>
        public static string EditTerminDoctor {
            get {
                return ResourceManager.GetString("EditTerminDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin durchgeführt.
        /// </summary>
        public static string EditTerminDone {
            get {
                return ResourceManager.GetString("EditTerminDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin abgemacht.
        /// </summary>
        public static string EditTerminFixed {
            get {
                return ResourceManager.GetString("EditTerminFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort.
        /// </summary>
        public static string EditTerminLocation {
            get {
                return ResourceManager.GetString("EditTerminLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminname.
        /// </summary>
        public static string EditTerminName {
            get {
                return ResourceManager.GetString("EditTerminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminperiode.
        /// </summary>
        public static string EditTerminPeriode {
            get {
                return ResourceManager.GetString("EditTerminPeriode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erinnern.
        /// </summary>
        public static string EditTerminRemind {
            get {
                return ResourceManager.GetString("EditTerminRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Termine.
        /// </summary>
        public static string MainMenuAppointments {
            get {
                return ResourceManager.GetString("MainMenuAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Behandlungen und Operation.
        /// </summary>
        public static string MainMenuOperation {
            get {
                return ResourceManager.GetString("MainMenuOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string MainMenuSettings {
            get {
                return ResourceManager.GetString("MainMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen bei deiner smarten Nachsorge!.
        /// </summary>
        public static string MainMenuWelcome {
            get {
                return ResourceManager.GetString("MainMenuWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchgeführte Termine.
        /// </summary>
        public static string OverviewDone {
            get {
                return ResourceManager.GetString("OverviewDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgemachte Termine.
        /// </summary>
        public static string OverviewFixed {
            get {
                return ResourceManager.GetString("OverviewFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geplante Termine.
        /// </summary>
        public static string OverviewPlanned {
            get {
                return ResourceManager.GetString("OverviewPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rektumkarzinom.
        /// </summary>
        public static string Rektumkarzinom {
            get {
                return ResourceManager.GetString("Rektumkarzinom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin speichern.
        /// </summary>
        public static string saveAppointment {
            get {
                return ResourceManager.GetString("saveAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen speichern.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karzinomart.
        /// </summary>
        public static string SettingsCarcinomType {
            get {
                return ResourceManager.GetString("SettingsCarcinomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP-Datum.
        /// </summary>
        public static string SettingsOPDate {
            get {
                return ResourceManager.GetString("SettingsOPDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string SettingsSchema {
            get {
                return ResourceManager.GetString("SettingsSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volles Stageing.
        /// </summary>
        public static string SettingsStageingComplete {
            get {
                return ResourceManager.GetString("SettingsStageingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TNM.
        /// </summary>
        public static string SettingsTNM {
            get {
                return ResourceManager.GetString("SettingsTNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Operationen.
        /// </summary>
        public static string Surgerys {
            get {
                return ResourceManager.GetString("Surgerys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Behandlungen.
        /// </summary>
        public static string Treatments {
            get {
                return ResourceManager.GetString("Treatments", resourceCulture);
            }
        }
    }
}
